apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: config-policy-controller-cb5l
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: config-policy-controller-cb5l
    app.kubernetes.io/part-of: config-policy-controller
  name: config-policy-controller-cb5l
  namespace: dfodor-tenant
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: config-policy-controller-cb5l
status:
  loadBalancer: {}
